### PR TITLE
Use card content_id and content_type if available

### PR DESCRIPTION
**Pull request by kmpaul**
This PR addresses the alternate way of creating Project Cards, namely with a `content_id` and `content_type` instead of a `note`.  If you manually create a card with a note field containing a valid content `html_url` for an issue or pull request, then the card actually gets created with `content_id` and `content_type`, meaning that the `note` field will be `None`.  This leads to a problem with the current logic of the bot.

However, if you create the cards (with the bot) using `content_id` and `content_type` *instead* of with the `note` field, then you do not have to do a second query of the GitHub API to retrieve the issue/PR's *state* ("open", "closed", etc.).  So, if you can create cards on the board that use the `content_id` and `content_type` parameters, then we can reduce our query rate, possibly leading to an increate is the polling frequency.

Addressed by this issue:
- Some minor parameter renaming
- Creates all cards on the Project Boards using `content_id` and `content_type` parameters (instead of `note`)
- Matches cards on the board to `content_id` *or* URL `ref`
- Gets the state of the issue/PR from the `content_state`, if available, during polling

### CODE REVIEW

**Comment by andersy005** [comment]
@kmpaul, I am curious... What happens to a card like this: https://github.com/NCAR/xdev/projects/1#card-36735263? Does it get parsed correctly?


The note section of this sample card contains:

```
I have a call scheduled with Frank B to help pull his fix for this issue into the repo

https://github.com/NCAR/pop-tools/issues/49
```

**Comment by kmpaul** [comment]
Yes.  It *should* get parsed correctly.

The function `utils.refs_from_note` will search the note for value GitHub Issue/PR references.  If there is 1 (and only 1!) reference in the `note`, then the card will be controlled by the bot.  (It doesn't actually care about the entire `note`, it just cares about any references in the note.  And since having 2 or more references in the note is ambiguous, it just ignores it if it has 2 or more references.)

**Comment by kmpaul** [comment]
However, you should note that with GitHub's adoption of the `content_id` and `content_type` specification (https://developer.github.com/v3/projects/cards/#create-a-project-card), you can *either* specify a `note` *or* `content_id` and `content_type`.

If you manually create a card with `note` that looks like this:

```text
https://github.com/NCAR/pop-tools/issues/49
```

Then GitHub will actually (behind the scenes) create the card with `content_id` and `content_type`.

The important thing to note, however, is that if you *do* create a card with `content_id` and `content_type`, then you cannot *also* have a `note` attached to the card.  So, it's one or the other.  I prefer the `content_id` and `content_type` approach because it allows you to request the *state* of the Issue/PR at the same time you query the cards on the boards.

**Comment by kmpaul** [comment]
Also, the *old* bot may not find the card properly, because it doesn't have a `refs_from_note`-like function.  I don't think.

**Comment by andersy005** [comment]
> Then GitHub will actually (behind the scenes) create the card with content_id and content_type.

Great... I wasn't aware of this. 


> Also, the old bot may not find the card properly, because it doesn't have a refs_from_note-like function.

That's right

**Pull request merged**
